name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 10.x, 14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm ci

      - name: Run tests
        run: npm test


        # e-commerce project
        env:
          CC_TEST_REPORTER_ID: '0f994c643098c5170ff39f19aae8b135c283a936c3403694a592b13bd6d72c7e'














          